services:
  tts-server:
    platform: linux/arm64
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "10108:10108"
    volumes:
      - ./config.json:/app/config.json
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped